from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from . import networks

from . import metrics, spaces, utils
from .base import (
    TAction,
    TBackwardAction,
    TDone,
    TEnvironment,
    TEnvParams,
    TEnvState,
    TLogReward,
    TObs,
    TReward,
    TRewardModule,
    TRewardParams,
)
from .environment import (
    AMPEnvironment,
    AMPEnvParams,
    AMPEnvState,
    BitseqEnvironment,
    BitseqEnvParams,
    BitseqEnvState,
    DAGEnvironment,
    DAGEnvParams,
    DAGEnvState,
    GFPEnvironment,
    GFPEnvParams,
    GFPEnvState,
    HypergridEnvironment,
    HypergridEnvParams,
    HypergridEnvState,
    IsingEnvironment,
    IsingEnvParams,
    IsingEnvState,
    PhyloTreeEnvironment,
    PhyloTreeEnvParams,
    PhyloTreeEnvState,
    QM9SmallEnvironment,
    QM9SmallEnvParams,
    QM9SmallEnvState,
    TFBind8Environment,
    TFBind8EnvParams,
    TFBind8EnvState,
)
from .reward import (
    AMPRewardParams,
    BaseDAGLikelihood,
    BaseDAGLikelihoodParams,
    BaseDAGPrior,
    BaseDAGPriorParams,
    BitseqRewardModule,
    BitseqRewardParams,
    DAGRewardModule,
    DAGRewardParams,
    EasyHypergridRewardModule,
    EqxProxyAMPRewardModule,
    EqxProxyGFPRewardModule,
    GeneralHypergridRewardModule,
    GFPRewardParams,
    HardHypergridRewardModule,
    HypergridRewardParams,
    IsingRewardModule,
    IsingRewardParams,
    PhyloTreeRewardModule,
    PhyloTreeRewardParams,
    QM9SmallRewardModule,
    QM9SmallRewardParams,
    TFBind8RewardModule,
    TFBind8RewardParams,
)
from .visualize import Visualizer

__all__ = [
    "AMPEnvParams",
    "AMPEnvState",
    "AMPEnvironment",
    "AMPRewardParams",
    "BaseDAGLikelihood",
    "BaseDAGLikelihoodParams",
    "BaseDAGPrior",
    "BaseDAGPriorParams",
    "BitseqEnvParams",
    "BitseqEnvState",
    "BitseqEnvironment",
    "BitseqRewardModule",
    "BitseqRewardParams",
    "DAGEnvParams",
    "DAGEnvState",
    "DAGEnvironment",
    "DAGRewardModule",
    "DAGRewardParams",
    "EasyHypergridRewardModule",
    "EqxProxyAMPRewardModule",
    "EqxProxyGFPRewardModule",
    "GFPEnvParams",
    "GFPEnvState",
    "GFPEnvironment",
    "GFPRewardParams",
    "GeneralHypergridRewardModule",
    "HardHypergridRewardModule",
    "HypergridEnvParams",
    "HypergridEnvState",
    "HypergridEnvironment",
    "HypergridRewardParams",
    "IsingEnvParams",
    "IsingEnvState",
    "IsingEnvironment",
    "IsingRewardModule",
    "IsingRewardParams",
    "PhyloTreeEnvParams",
    "PhyloTreeEnvState",
    "PhyloTreeEnvironment",
    "PhyloTreeRewardModule",
    "PhyloTreeRewardParams",
    "QM9SmallEnvParams",
    "QM9SmallEnvState",
    "QM9SmallEnvironment",
    "QM9SmallRewardModule",
    "QM9SmallRewardParams",
    "TAction",
    "TBackwardAction",
    "TDone",
    "TEnvParams",
    "TEnvState",
    "TEnvironment",
    "TFBind8EnvParams",
    "TFBind8EnvState",
    "TFBind8Environment",
    "TFBind8RewardModule",
    "TFBind8RewardParams",
    "TLogReward",
    "TObs",
    "TReward",
    "TRewardModule",
    "TRewardParams",
    "Visualizer",
    "metrics",
    "networks",
    "spaces",
    "utils",
]

# Lazy import of networks since networks are based on Equinox
import importlib


def __getattr__(name):
    if name == "networks":
        return importlib.import_module(f"{__name__}.networks")
    raise AttributeError(f"module {__name__} has no attribute {name}")


def __dir__():
    return __all__
